### PR TITLE
memory leak fix for 4.2.2 

### PR DESCRIPTION
**Pull request by soldair**
this is a fix for the 4.2.2 series. Ideally this can go out in a 4.2.3 patch release. This will allow the leak to be fixed in first-mate and atom while we wait for  5.x to compile on older node versions.

It differs because the use of Nan::Global is an error in node 0.10 so i rolled back to using icky ifdefs to call either Dispose or Reset on the Persistent via the OnigStringContext destructor.

This maintains the existing compatibility table for the current 4.2.2 series.
Tested on node 0.10.40, 0.12.7, and iojs 2.5
This module fails to build on iojs 3.x and node 4.x just like the current 4.2.2 release.

this is fairly high priority for me because I'm using a fork of oniguruma, first-mate, highlights, and marky-markdown to render readmes in npm/newww where i have to suppprt node 0.10 for a bit longer.

### CODE REVIEW

**Comment by soldair** [comment]
i don't want this to go into ataom master but rather a branch based off of 4.2.2

**Comment by soldair** [comment]
@zcbenz if this change is acceptable could you create a 4.x-dev branch ill reopen this pull against it?

**Comment by zcbenz** [comment]
How about making v5.x work for node v0.10? I can try fixing that.

**Comment by soldair** [comment]
that would be so great. it's still a good idea to push a 4.2.3 maintenance release because of existing modules that are including the version that leaks =/. 

Are their js api changes that caused the project to change the major? it will require an npm publish for first-mate and atom and a few others.

**Comment by zcbenz** [comment]
Closed in favor of #38.

**Comment by soldair** [comment]
@zcbenz just in casse you missed this because i posted just as you closed this please consider a 4.2.3 release.

**Comment by zcbenz** [comment]
I bumped the major version because an upgrade of Nan is very likely to break things, and I don't want to break current builds of Atom and other projects.

I have created the `v4.x` so you can create a PR against it.

**Comment by soldair** [comment]
thanks!

**Pull request closed without merging**
