### PR TITLE
Only minor syntactic sugar removed from ES6 to ES5

### LINKED ISSUE #65: Support for Node 4 lost in latest minor release
https://github.com/atom/node-oniguruma/commit/80716271c26bfc02300d599f83b954676f892a48#diff-4cb512c0b8c044091a83b49d95f77ddcR1

With the addition of destructuring assignments, this only supports node 6 now.

### PR DESCRIPTION
**Pull request by elingerojo**
Fixes #65 

### Approach

1. One step, one commit. For easy review.
2. Start by setting the wanted Node support to work toward getting the Travis CI green arrow.
3. Only remove syntactic sugar to be ES5 compatible
4. Squash commits at merge if desired

### CODE REVIEW

**Comment by zeke** [comment]
It looks like `class OnigRegExp` was already commented out. What about just removing that code instead of converting it to ES5?

**Comment by elingerojo** [comment]
I did the comment out after converting to ES5 and left the comments for easy review.
The change is needed to get back Node 4 support

- Updated with a new [commit](https://github.com/atom/node-oniguruma/pull/66/commits/b77195a99f765a0243e47b727021e29a60bab52d) with comments removed just now

**Comment by zeke** [comment]
Looks good to me. What do you think, @maxbrunsfeld?

**Comment by ashleygwilliams** [comment]
would love to know the status on this!

**Comment by zeke** [comment]
Let's make it happen?

Do we want to first update the travis config to test on more node versions? 4, 6, 8?

**Comment by ashleygwilliams** [comment]
thanks @zeke! 4, 6, and 8 seems good to me. i'm happy to make the travis PR if you'd like as well. just lemme know!

**Comment by ashleygwilliams** [comment]
@zeke actually i just opened https://github.com/atom/node-oniguruma/pull/70 ;) waiting on travis now

**Comment by ashleygwilliams** [comment]
@zeke ? would love to get this merged

**Comment by zeke** [comment]
I want to see this passing on node 4, 6, and 8 first. I can't edit this PR, so I've opened a followup to it: https://github.com/atom/node-oniguruma/pull/71

**Pull request closed without merging**
